version: "3.9"

services:
  db:
    image: postgres:15
    container_name: used-furniture-db
    environment:
      POSTGRES_DB: usedfurniture
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
