services:
  - type: web
    name: used-furniture-backend
    env: docker
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/used-furniture-app-1.0-SNAPSHOT.jar
    envVars:
      - key: DB_HOST
        value: your-db-host.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: usedfurniture
      - key: DB_USER
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
