spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/usedfurniture
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

app:
  upload:
    dir: /mnt/e/uploads
