spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/usedfurniture
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
